""""Add core models"

Revision ID: baeefa6fe33e
Revises:
Create Date: 2022-06-19 18:04:17.755861

"""
from alembic import op
import sqlalchemy as sa
import smitepaper.models
import smitepaper.types

# revision identifiers, used by Alembic.
revision = "baeefa6fe33e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("pantheon", sa.String(length=255), nullable=False),
        sa.Column(
            "attack_type",
            smitepaper.types.IntEnum(smitepaper.models.God.AttackType),
            nullable=False,
        ),
        sa.Column(
            "power_type",
            smitepaper.types.IntEnum(smitepaper.models.God.PowerType),
            nullable=False,
        ),
        sa.Column(
            "class_type",
            smitepaper.types.IntEnum(smitepaper.models.God.ClassType),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            smitepaper.types.IntEnum(smitepaper.models.God.DifficultyType),
            nullable=False,
        ),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallpapers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.Column("size", sa.String(length=9), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallpaper_tags",
        sa.Column("wallpaper_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallpaper_id"],
            ["wallpapers.id"],
        ),
        sa.PrimaryKeyConstraint("wallpaper_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallpaper_tags")
    op.drop_table("wallpapers")
    op.drop_table("tags")
    op.drop_table("gods")
    # ### end Alembic commands ###
